import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavLink } from "src/components/NavLink";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="box">
          <h1 className="title2">RootLayout</h1>
          <nav className="flex space-x-4 bg-gray-100 p-4 rounded-md shadow-md">
            <NavLink href="/">home</NavLink>
            <NavLink href="/dashboard">dashboard</NavLink>
            <NavLink href="/dashboard/setting">dashboard setting</NavLink>
            <NavLink href="/about">about</NavLink>
            <NavLink href="/more">more</NavLink>
            <NavLink href="/team/123">team</NavLink>
            <NavLink href="/suspense">suspense</NavLink>
            <NavLink href="/product/789">product</NavLink>
            <NavLink href="/blog">blog</NavLink>
            <NavLink href="/list">list</NavLink>
            <NavLink href="/list/detail">detail</NavLink>
          </nav>
          <article
            className="p-4 bg-gray-100 rounded-md shadow-md"
            style={{ minHeight: "calc(100vh - 4rem)" }}
          >
            {children}
          </article>
        </main>
      </body>
    </html>
  );
}
